vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/config/routes.rb
# frozen_string_literal: true

LetterOpenerWeb::Engine.routes.draw do
  get  '/'                     => 'letters#index',    as: :letters
  post 'clear'                 => 'letters#clear',    as: :clear_letters
  get  ':id(/:style)'          => 'letters#show',     as: :letter
  post ':id/delete'            => 'letters#destroy',  as: :delete_letter
  get  ':id/attachments/:file' => 'letters#attachment'
end

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/models/letter_opener_web/letter.rb
# frozen_string_literal: true

module LetterOpenerWeb
  class Letter
    attr_reader :id, :sent_at

    def self.letters_location
      @letters_location ||= LetterOpenerWeb.config.letters_location
    end

    def self.letters_location=(directory)
      LetterOpenerWeb.configure { |config| config.letters_location = directory }
      @letters_location = nil
    end

    def self.search
      letters = Dir.glob("#{LetterOpenerWeb.config.letters_location}/*").map do |folder|
        new(id: File.basename(folder), sent_at: File.mtime(folder))
      end
      letters.sort_by(&:sent_at).reverse
    end

    def self.find(id)
      new(id: id)
    end

    def self.destroy_all
      FileUtils.rm_rf(LetterOpenerWeb.config.letters_location)
    end

    def initialize(params)
      @id      = params.fetch(:id)
      @sent_at = params[:sent_at]
    end

    def headers
      html = read_file(:rich) if style_exists?('rich')
      html ||= read_file(:plain)

      # NOTE: This is ugly, we should look into using nokogiri and making that a
      # dependency of this gem
      match_data = html.match(%r{<body>\s*<div[^>]+id="container">\s*<div[^>]+id="message_headers">\s*(<dl>.+</dl>)}m)
      return remove_attachments_link(match_data[1]).html_safe if match_data && match_data[1].present?

      'UNABLE TO PARSE HEADERS'
    end

    def plain_text
      @plain_text ||= adjust_link_targets(read_file(:plain))
    end

    def rich_text
      @rich_text ||= adjust_link_targets(read_file(:rich))
    end

    def to_param
      id
    end

    def default_style
      style_exists?('rich') ? 'rich' : 'plain'
    end

    def attachments
      @attachments ||= Dir["#{base_dir}/attachments/*"].each_with_object({}) do |file, hash|
        hash[File.basename(file)] = File.expand_path(file)
      end
    end

    def delete
      return unless valid?

      FileUtils.rm_rf(base_dir.to_s)
    end

    def valid?
      exists? && base_dir_within_letters_location?
    end

    private

    def remove_attachments_link(headers)
      xml = REXML::Document.new(headers)
      if xml.root.elements.size == 10
        xml.delete_element('//dd[last()]')
        xml.delete_element('//dt[last()]')
      end
      xml.to_s
    end

    def base_dir
      LetterOpenerWeb.config.letters_location.join(id).cleanpath
    end

    def read_file(style)
      File.read("#{base_dir}/#{style}.html")
    end

    def style_exists?(style)
      File.exist?("#{base_dir}/#{style}.html")
    end

    def exists?
      File.exist?(base_dir)
    end

    def base_dir_within_letters_location?
      base_dir.to_s.start_with?(LetterOpenerWeb.config.letters_location.to_s)
    end

    def adjust_link_targets(contents)
      # We cannot feed the whole file to a XML parser as some mails are
      # "complete" (as in they have the whole <html> structure) and letter_opener
      # prepends some information about the mail being sent, making REXML
      # complain about it
      contents.scan(%r{<a\s[^>]+>(?:.|\s)*?</a>}).each do |link|
        fixed_link = fix_link_html(link)
        xml        = REXML::Document.new(fixed_link).root
        next if xml.attributes['href'] =~ /(plain|rich).html/

        xml.attributes['target'] = '_blank'
        xml.add_text('') unless xml.text
        contents.gsub!(link, xml.to_s)
      end
      contents
    end

    def fix_link_html(link_html)
      # REFACTOR: we need a better way of fixing the link inner html
      link_html.dup.tap do |fixed_link|
        fixed_link.gsub!('<br>', '<br/>')
        fixed_link.scan(/<img(?:[^>]+?)>/).each do |img|
          fixed_img = img.dup
          fixed_img.gsub!(/>$/, '/>') unless img =~ %r{/>$}
          fixed_link.gsub!(img, fixed_img)
        end
      end
    end
  end
end

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/controllers/letter_opener_web/application_controller.rb
# frozen_string_literal: true

module LetterOpenerWeb
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception, unless: -> { Rails.configuration.try(:api_only) }
  end
end

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/controllers/letter_opener_web/letters_controller.rb
# frozen_string_literal: true

unless Rails.respond_to?(:autoloaders) && Rails.autoloaders.zeitwerk_enabled?
  require_dependency 'letter_opener_web/application_controller'
end

module LetterOpenerWeb
  class LettersController < ApplicationController
    before_action :check_style, only: :show
    before_action :load_letter, only: %i[show attachment destroy]

    def index
      @letters = LetterOpenerWeb::Letter.search
    end

    def show
      text = @letter.send("#{params[:style]}_text")
                    .gsub(/"plain\.html"/, "\"#{routes.letter_path(id: @letter.id, style: 'plain')}\"")
                    .gsub(/"rich\.html"/, "\"#{routes.letter_path(id: @letter.id, style: 'rich')}\"")

      render html: text.html_safe
    end

    def attachment
      filename = "#{params[:file]}.#{params[:format]}"
      file     = @letter.attachments[filename]

      return render plain: 'Attachment not found!', status: 404 unless file.present?

      send_file(file, filename: filename, disposition: 'inline')
    end

    def clear
      LetterOpenerWeb::Letter.destroy_all
      redirect_to routes.letters_path
    end

    def destroy
      @letter.delete
      respond_to do |format|
        format.html { redirect_to routes.letters_path }
        format.js { render js: "window.location='#{routes.letters_path}'" }
      end
    end

    private

    def check_style
      params[:style] = 'rich' unless %w[plain rich].include?(params[:style])
    end

    def load_letter
      @letter = LetterOpenerWeb::Letter.find(params[:id])

      head :not_found unless @letter.valid?
    end

    def routes
      LetterOpenerWeb.railtie_routes_url_helpers
    end
  end
end

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/layouts/letter_opener_web/_javascripts.html.erb
<%= render "layouts/letter_opener_web/js/jquery" %>
<%= render "layouts/letter_opener_web/js/favcount" %>

<script nonce="<%= content_security_policy_nonce %>">
function update_favicon(favicon) {
    favicon.set($('.letter-opener a').length);
}

jQuery(function($) {
    var favicon = new Favcount($('link[rel="icon"]').attr('href'));
    update_favicon(favicon);

    $('.letter-opener').on('click', 'a', function() {
        var $this = $(this);
        $('iframe').attr('src', $this.attr('href'));
        $this.parents('.list-group').find('.active').removeClass('active');
        $this.parent().addClass('active');
    });

    $('.refresh').click(function(e) {
        e.preventDefault();

        var wrapper = $('.letter-opener');
        wrapper.find('div').text('Loading...');
        wrapper.load(wrapper.data('letters-path') + ' .letter-opener', function() {
            $('iframe').attr('src', $('.letter-opener a:first-child()').attr('href'));
            update_favicon(favicon);
        });
    });
});
</script>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/layouts/letter_opener_web/_styles.html.erb
<%= render "layouts/letter_opener_web/styles/icon" %>
<%= render "layouts/letter_opener_web/styles/bootstrap" %>
<%= render "layouts/letter_opener_web/styles/letters" %>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/layouts/letter_opener_web/js/_favcount.html.erb
<script nonce="<%= content_security_policy_nonce %>">
/*
 * favcount.js v1.5.0
 * http://chrishunt.co/favcount
 * Dynamically updates the favicon with a number.
 *
 * Copyright 2013, Chris Hunt
 * Released under the MIT license
 */

(function(){
  function Favcount(icon) {
    this.icon = icon;
    this.opacity = 0.4;
    this.canvas = document.createElement('canvas');
    this.font = "Helvetica, Arial, sans-serif";
  }

  Favcount.prototype.set = function(count) {
    var self = this,
        img  = document.createElement('img');

    if (self.canvas.getContext) {
      img.crossOrigin = "anonymous";

      img.onload = function() {
        drawCanvas(self.canvas, self.opacity, self.font, img, normalize(count));
      };

      img.src = this.icon;
    }
  };

  function normalize(count) {
    count = Math.round(count);

    if (isNaN(count) || count < 1) {
      return '';
    } else if (count < 10) {
      return ' ' + count;
    } else if (count > 99) {
      return '99';
    } else {
      return count;
    }
  }

  function drawCanvas(canvas, opacity, font, img, count) {
    var head = document.getElementsByTagName('head')[0],
        favicon = document.querySelector('link[rel=icon]'),
        newFavicon = document.createElement('link'),
        multiplier, fontSize, context, xOffset, yOffset, border, shadow;

    // Scale canvas elements based on favicon size
    multiplier = img.width / 16;
    fontSize   = multiplier * 11;
    xOffset    = multiplier;
    yOffset    = multiplier * 11;
    border     = multiplier;
    shadow     = multiplier * 2;

    canvas.height = canvas.width = img.width;
    context = canvas.getContext('2d');
    context.font = 'bold ' + fontSize + 'px ' + font;

    // Draw faded favicon background
    if (count) { context.globalAlpha = opacity; }
    context.drawImage(img, 0, 0);
    context.globalAlpha = 1.0;

    // Draw white drop shadow
    context.shadowColor = '#FFF';
    context.shadowBlur = shadow;
    context.shadowOffsetX = 0;
    context.shadowOffsetY = 0;

    // Draw white border
    context.fillStyle = '#FFF';
    context.fillText(count, xOffset, yOffset);
    context.fillText(count, xOffset + border, yOffset);
    context.fillText(count, xOffset, yOffset + border);
    context.fillText(count, xOffset + border, yOffset + border);

    // Draw black count
    context.fillStyle = '#000';
    context.fillText(count,
      xOffset + (border / 2.0),
      yOffset + (border / 2.0)
    );

    // Replace favicon with new favicon
    newFavicon.rel = 'icon';
    newFavicon.href = canvas.toDataURL('image/png');
    if (favicon) { head.removeChild(favicon); }
    head.appendChild(newFavicon);
  }

  this.Favcount = Favcount;
}).call(this);

(function(){
  Favcount.VERSION = '1.5.1';
}).call(this);
</script>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/layouts/letter_opener_web/letters.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LetterOpenerWeb</title>
  <%= render "layouts/letter_opener_web/styles" %>
  <% if respond_to? :csp_meta_tag %>
    <%= csp_meta_tag %>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= render "layouts/letter_opener_web/javascripts" %>
</body>
</html>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/layouts/letter_opener_web/styles/_letters.html.erb
<style>
  body {
    margin: 0
  }

  .col {
    top:      0;
    bottom:   0;
  }

  .left {
    overflow-y: auto;
    width:      350px;
    position:   absolute;
  }

  .right {
    left:     350px;
    right:    0;
    position: fixed;
  }

  iframe {
    width:      100%;
    height:     100%;
    position:   absolute;
    border:     solid 1px #ccc;
    border-top: none;
  }

  h1 {
    padding-right: 10px;
    padding-left:  5px;
  }

  .message-headers a {
    color: black;
  }

  .message-headers.active a {
    color: white;
  }

  .message-headers dl {
    float: left;
    font-size: 0.8rem;
    padding: 0;
    margin: 0;
  }

  .message-headers dt {
    width: 60px;
    margin: 0;
    float: left;
    font-weight: bold;
  }

  .message-headers dd {
    margin: 0 0 0 60px;
  }

  .message-headers p.alternate {
    float: right;
    margin: 0;
  }

  .message-headers p.alternate a {
    color: #09c;
  }
</style>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/letter_opener_web/letters/_item.html.erb
<% classes = %w(list-group-item list-group-action d-flex justify-content-between align-items-start p-2 message-headers) %>
<% classes << 'active' if active %>
<%= content_tag :li, class: classes do %>
  <%= link_to(letter_path(letter, style: letter.default_style), target: 'mail') do %>
    <%= letter.headers %>
  <% end %>
  <button class="btn btn-danger btn-sm" data-remote="true" data-url="<%= delete_letter_path(letter) %>" data-method="post" data-confirm="Are you sure?">
    <strong><small>X</small></strong>
  </button>
<% end %>

vender/bundle/ruby/3.0.0/gems/letter_opener_web-2.0.0/app/views/letter_opener_web/letters/index.html.erb
<div class="col left">
  <h1>
    Letters
    <span class="float-end">
      <%= link_to letters_path, class: 'btn btn-primary refresh' do %>
        Refresh
      <% end %>
      <%= link_to clear_letters_path, method: 'post', data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
        Clear
      <% end %>
    </span>
  </h1>
    <div class="letter-opener" data-letters-path="<%= letters_path %>">
      <ul class="list-group rounded-0 pt-2">
        <% if first_letter = @letters.shift %>
          <%= render partial: "item", locals: { letter: first_letter, active: true } %>
        <% end %>
        <%= render partial: "item", collection: @letters, as: :letter, locals: { active: false } %>
      </ul>
    </div>
</div>
<div class="col right">
  <iframe name="mail" id="mail" src="<%= first_letter.present? ? letter_path(first_letter, style: first_letter.default_style) : 'about:blank' %>"></iframe>
</div>